### ISSUE TITLE
Post on Jekyll + HTML Proofer and why you should CI your prose

### ISSUE THREAD

**Issue by benbalter** [benbalter/benbalter.github.com#230]

**Comment by dannychapman** [comment]
:+1:

**Comment by parkr** [comment]
Interesting discussion around this in recent Jekyll issues. It's considered flaky -- ideally it only proofs your segment of the site. Otherwise, PR's get off-topic and the red X slows down or discourages contributors. A trade-off. 
Ex: jekyllrb.com links out to some blog post someone wrote. They recently added SSL support, but for whatever reason, HTML Proofer explodes when trying to make an SSL connection to the site. I can open it just fine in my browser, so I had to just ignore it, which isn't ideal. Even after the site owner added the intermediate and root certificates to his cert chain, it was still failing. Contributors got upset because they had a red X by no fault of their own.

**Comment by benbalter** [comment]
I've seen some magic (believe it was @gjtorikian's doing) that allowed it to only run on what was changed in a PR, thus it'd only go red in your example, if the link being added broke the build, not if the build was broken on master due to somebody else.

**Comment by gjtorikian** [comment]
That was @holman's doing, but I'll take credit for it! The code was:

``` ruby
    def posts
      diffable_files = `git diff --name-only --diff-filter=ACMRTUXB origin/master... | grep .md`.split("\n")

      posts = diffable_files.select do |filename|
        File.ctime(filename) > Time.new(2014,9,3)
      end

      posts
    end
```

**Comment by parkr** [comment]
Oh interesting! We should consider adding this to http://jekyllrb.com/docs/continuous-integration/
