### ISSUE TITLE
Suggestion: "Edit" link in posts to auto-fork

### ISSUE THREAD

**Issue by PedroLamas** [benbalter/benbalter.github.com#420]
Currently, when I click on the `Edit` link in your posts, this is what I see:

![image](https://cloud.githubusercontent.com/assets/85504/24709320/66a746ba-1a11-11e7-93eb-7896f1fb1bc8.png)

I'm using a similar approach on [my blog](https://www.pedrolamas.com), but I noticed that the `Edit` links inside GitHub submit a `form` that auto-forks the repo and edits the post in a single operation!

This does seem a bit too invasive, but it's quite faster to the readers/editors so I'm considering this approach... and I wanted your opinion if this is something you'd use!

What are your thoughts on this? 😄

**Comment by benbalter** [comment]
You'd have to use javascript to submit a POST or PUT request (whatever the form uses). In that case, I don't know that it's clear users will understand (and consent) to what they're doing (e.g., creating a copy of your content in their account), which is why I went the interstitial route which makes it clear what they're doing and provides links to additional context.

**Comment by pedrolamas** [comment]
Agreed! Though this is the "longer path", editors will have more control and will be directly asked for permission to fork repo before they can actually edit the post.
